[package]
name = "hack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
clap = "4.5.4"
clap_derive = "4.5.4"
pest = "2.7.10"
pest_derive = "2.7.10"
