[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow ={workspace=true}
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.119"

#[dependencies.rusqlite]
#version = "0.30.0"
#features = ["bundled"]
