program = _{ SOI ~ statement* ~ EOI }

statement = _{
    push_st
  | pop_st
  | add_st
  | sub_st
  | neg_st
  | eq_st
  | gt_st
  | lt_st
  | and_st
  | or_st
  | not_st
  | comment
  | NEWLINE
}
push_st   =  { "push" ~ segment ~ index }
pop_st    =  { "pop" ~ segment ~ index }
add_st    =  { "add" }
sub_st    =  { "sub" }
neg_st    =  { "neg" }
eq_st     =  { "eq" }
gt_st     =  { "gt" }
lt_st     =  { "lt" }
and_st    =  { "and" }
or_st     =  { "or" }
not_st    =  { "not" }

segment    = _{ argument | local | static_seg | constant | this | that | pointer | temp }
argument   =  { "argument" }
local      =  { "local" }
static_seg =  { "static" }
constant   =  { "constant" }
this       =  { "this" }
that       =  { "that" }
pointer    =  { "pointer" }
temp       =  { "temp" }
index      = _{ int }
comment    = _{ "//" ~ (!"\n" ~ ANY)* }
int        =  { ("+" | "-")? ~ ASCII_DIGIT+ }
hex        =  { '0'..'9' | 'a'..'f' | 'A'..'F' }
hex_num    =  { "0X" | "0x" ~ hex+ }
WHITESPACE = _{ " " | "\t" }
